spring:
  application:
    name: bootiful-audio
  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      audio:
        transcription:
          options:
            model: whisper-1
  security:
    user:
      name: ${APP_USER:user}
      password: ${APP_PASSWORD:password}
      roles: USER

vaadin:
  frontend:
    hotdeploy: false
