name: Build and Deploy Spring Boot App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'corretto'
          cache: maven

      - name: Build with Maven
        run: ./mvnw package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: target/bootiful-audio.jar
          retention-days: 1
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3

      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: app
          path: target

      - name: List files
        run: ls -la target/

      - name: Trigger Coolify Deployment
        run: |
          curl -X POST ${{ secrets.COOLIFY_WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d '{"ref": "${{ github.ref }}", "repository": {"url": "${{ github.repository }}"}}' \
            --fail
